// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcE2iFP6P5wkrDJ6USSW_W2-awFuS6c-0',
    appId: '1:930852921633:web:ee27ebf07604f19c1e1e60',
    messagingSenderId: '930852921633',
    projectId: 'finalproject-65682',
    authDomain: 'finalproject-65682.firebaseapp.com',
    storageBucket: 'finalproject-65682.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQZS6WfKtH68YLzmNZLm-jlVx5pKgjVrc',
    appId: '1:930852921633:android:d0b0939c253e2b8b1e1e60',
    messagingSenderId: '930852921633',
    projectId: 'finalproject-65682',
    storageBucket: 'finalproject-65682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwSbL7l7KfprdgUTVDGXouIxZzGYUfQw',
    appId: '1:930852921633:ios:10c2278ff358245f1e1e60',
    messagingSenderId: '930852921633',
    projectId: 'finalproject-65682',
    storageBucket: 'finalproject-65682.appspot.com',
    iosBundleId: 'com.example.stagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwSbL7l7KfprdgUTVDGXouIxZzGYUfQw',
    appId: '1:930852921633:ios:10c2278ff358245f1e1e60',
    messagingSenderId: '930852921633',
    projectId: 'finalproject-65682',
    storageBucket: 'finalproject-65682.appspot.com',
    iosBundleId: 'com.example.stagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcE2iFP6P5wkrDJ6USSW_W2-awFuS6c-0',
    appId: '1:930852921633:web:fd595ddc9e5d13931e1e60',
    messagingSenderId: '930852921633',
    projectId: 'finalproject-65682',
    authDomain: 'finalproject-65682.firebaseapp.com',
    storageBucket: 'finalproject-65682.appspot.com',
  );
}
